title: [Emma Zukow]
onaltitle: Emma Zukow
description: 
  <br> <br>
  Welcome to my portfolio!
  <br> <br>
  # I am an undergraduate student at <a href="https://www.dal.ca/">Dalhousie University</a> in Halifax, NS and I will be graduating in May 2021, with a BSc in Psychology and minor in Health Studies.
  I am so beautiful and forever grateful for my boyfriend he is perfect


theme: jekyll-theme-minimal
logo: IMG_5219.JPEG



github:
  is_project_page: false
