title: [Emma Zukow]
onaltitle: Emma Zukow
description: 
  <br> <br>
  Welcome to my portfolio!
  <br> <br>
  I am so beautiful and forever grateful for my boyfriend he is perfect


theme: jekyll-theme-minimal
logo: IMG_5219.JPEG



github:
  is_project_page: false
