shtitle: [Emma J. Zukow]
onaltitle: Emma Zukow
description: 
  <br> <br>
  Welcome to my portfolio!
  <br> <br>
  Info about me


theme: jekyll-theme-minimal
logo: emma.png



github:
  is_project_page: false
