shtitle: [Emma Zukow]
onaltitle: Emma Zukow
description: 
  <br> <br>
  Welcome to my portfolio!
  <br> <br>
  I am so beautiful and forever grateful for my boyfriend he is perfect


theme: jekyll-theme-minimal
logo: emma.png



github:
  is_project_page: false
